[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

# Optional but recommended
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
